package BancoChibchaController;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-09-01T19:04:21.593-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://controller/", name = "IConsultaPrestamoPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IConsultaPrestamoPortType {

    @WebMethod
    @RequestWrapper(localName = "consultaPrestamo", targetNamespace = "http://controller/", className = "BancoChibchaController.ConsultaPrestamo")
    @ResponseWrapper(localName = "consultaPrestamoResponse", targetNamespace = "http://controller/", className = "BancoChibchaController.ConsultaPrestamoResponse")
    @WebResult(name = "return", targetNamespace = "http://controller/")
    public BancoChibchaController.String2StringHashMap consultaPrestamo();
}
